from selenium.webdriver.common.by import By



button_order_on_the_header = [By.CLASS_NAME, 'Button_Button__ra12g']
button_order_on_the_middle = [By.CLASS_NAME, 'Button_Button__ra12g Button_UltraBig__UU3Lp']
button_order_on_the_form = [By.XPATH, '//*[@id="root"]/div/div[2]/div[3]/button[2]']
button_yes = [By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/div[2]/button[2]']
field_firstname_in_the_order_form = [By.CSS_SELECTOR, '#root > div > div.Order_Content__bmtHS > div.Order_Form__17u6u > div:nth-child(1) > input']
field_secondname_in_the_order_form = [By.CSS_SELECTOR, '#root > div > div.Order_Content__bmtHS > div.Order_Form__17u6u > div:nth-child(2) > input']
field_adress_in_the_order_form = [By.CSS_SELECTOR, '#root > div > div.Order_Content__bmtHS > div.Order_Form__17u6u > div:nth-child(3) > input']
field_station_in_the_order_form = [By.CSS_SELECTOR, '#root > div > div.Order_Content__bmtHS > div.Order_Form__17u6u > div:nth-child(4) > div > div > input']
station_menu = [By.CLASS_NAME, 'select-search__value']
field_phonenumber_in_the_order_form = [By.CSS_SELECTOR, '#root > div > div.Order_Content__bmtHS > div.Order_Form__17u6u > div:nth-child(5) > input']
button_next_in_the_order_form = [By.XPATH, '//*[@id="root"]/div/div[2]/div[3]/button']
link_logo_scooter = [By.CLASS_NAME, 'Header_LogoScooter__3lsAR']
link_logo_yandex = [By.CLASS_NAME, 'Header_LogoYandex__3TSOI']
data_order = [By.CSS_SELECTOR, '#root > div > div.Order_Content__bmtHS > div.Order_Form__17u6u > div.Order_MixedDatePicker__3qiay > div.react-datepicker-wrapper > div > input']
rental_time = [By.CSS_SELECTOR, '#root > div > div.Order_Content__bmtHS > div.Order_Form__17u6u > div.Dropdown-root > div']
color_scooter = [By.CSS_SELECTOR, '#root > div > div.Order_Content__bmtHS > div.Order_Form__17u6u > div.Order_Checkboxes__3lWSI.Order_FilledContainer__2MKAk']
comment_for_courier = [By.CSS_SELECTOR, '#root > div > div.Order_Content__bmtHS > div.Order_Form__17u6u > div.Input_InputContainer__3NykH > input']
time_delivery = [By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[2]/div[2]/div[2]']
black_color_scooter = [By.ID, 'black']
modal_window_order = [By.CLASS_NAME, 'Order_ModalHeader__3FDaJ']
logo_yandex = [By.CLASS_NAME, 'home-logo__default']
header_text_main_page_scooter = [By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[4]']
view_status_button = [By.XPATH, '/html/body/div/div/div[2]/div[5]/div[2]/button']
modal_close = [By.XPATH, '/html/body/div[2]/div/div/div/div/div[5]']
question_button_1 = [By.ID, 'accordion__heading-0']
answer_button_1 = [By.ID, 'accordion__panel-0']
question_button_2 = [By.ID, 'accordion__heading-1']
answer_button_2 = [By.ID, 'accordion__panel-1']
question_button_3 = [By.ID, 'accordion__heading-2']
answer_button_3 = [By.ID, 'accordion__panel-2']
question_button_4 = [By.ID, 'accordion__heading-3']
answer_button_4 = [By.ID, 'accordion__panel-3']
question_button_5 = [By.ID, 'accordion__heading-4']
answer_button_5 = [By.ID, 'accordion__panel-4']
question_button_6 = [By.ID, 'accordion__heading-5']
answer_button_6 = [By.ID, 'accordion__panel-5']
question_button_7 = [By.ID, 'accordion__heading-6']
answer_button_7 = [By.ID, 'accordion__panel-6']
question_button_8 = [By.ID, 'accordion__heading-7']
answer_button_8 = [By.ID, 'accordion__panel-7']